AWS_ACCESS_KEY_ID= ENV['AWS_ACCESS_KEY_ID']
AWS_SECRET_ACCESS_KEY= ENV['AWS_SECRET_ACCESS_KEY']
SimpleRecord.establish_connection(AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY, :connection_mode=>:per_thread)
